#!/system/bin/sh
# HEBF
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

mount -o remount,rw /system

busybox sed -i '/ro.ril.hsxpa=2/d' /system/build.prop
busybox sed -i '/ro.ril.hep=1/d' /system/build.prop
busybox sed -i '/ro.ril.enable.dtm=1/d' /system/build.prop
busybox sed -i '/ro.ril.hsdpa.category=10/d' /system/build.prop
busybox sed -i '/ro.ril.enable.a53=1/d' /system/build.prop
busybox sed -i '/ro.ril.enable.3g.prefix=1/d' /system/build.prop
busybox sed -i '/ro.ril.gprsclass=10/d' /system/build.prop
busybox sed -i '/ro.ril.hsupa.category=7/d' /system/build.prop
busybox sed -i '/ro.ril.hsdpa.category=10/d' /system/build.prop
busybox sed -i '/ro.ril.enable.a52=1/d' /system/build.prop
busybox sed -i '/ro.ril.set.mtu1472=1/d' /system/build.prop
busybox sed -i '/persist.cust.tel.eons=1/d' /system/build.prop

setprop ro.ril.hsxpa 2
setprop ro.ril.hep 1
setprop ro.ril.enable.dtm 1
setprop ro.ril.hsdpa.category 10
setprop ro.ril.enable.a53 1
setprop ro.ril.enable.3g.prefix 1
setprop ro.ril.gprsclass 10
setprop ro.ril.hsupa.category 7
setprop ro.ril.hsdpa.category 10
setprop ro.ril.enable.a52 1
setprop ro.ril.set.mtu1472 1
setprop persist.cust.tel.eons 1

busybox echo "#3G tweaks added $(date +%A), $(date +%H:%M)" >> /data/data/com.androidvip.hebf/hebf_logs/app.log

mount -o remount,ro /system
