#!/system/bin/sh
# HEBF
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

mount -o remount,rw /system

echo "500" > /proc/sys/vm/dirty_expire_centisecs;
echo "1000" > /proc/sys/vm/dirty_writeback_centisecs

busybox sed -i '/ro.ril.disable.power.collapse=0/d' /system/build.prop
busybox sed -i '/pm.sleep_mode=1/d' /system/build.prop
busybox sed -i '/persist.android.strictmode=0/d' /system/build.prop
busybox sed -i '/persist.sys.purgeable_assets=1/d' /system/build.prop
busybox sed -i '/ro.com.google.networklocation=0/d' /system/build.prop
busybox sed -i '/ro.kernel.android.checkjni=0/d' /system/build.prop
busybox sed -i '/ro.config.nocheckin=1/d' /system/build.prop
busybox sed -i '/ro.vold.umsdirtyratio=20/d' /system/build.prop
busybox sed -i '/dalvik.vm.checkjni=false/d' /system/build.prop
busybox sed -i '/ro.vold.umsdirtyratio=int:jit/d' /system/build.prop
busybox sed -i '/profiler.force_disable_err_rpt=1/d' /system/build.prop
busybox sed -i '/profiler.force_disable_ulog=1/d' /system/build.prop
busybox sed -i '/ro.ril.disable.power.collapse=0/d' /system/build.prop
busybox sed -i '/pm.sleep_mode=1/d' /system/build.prop
busybox sed -i '/ro.com.google.networklocation=0/d' /system/build.prop
busybox sed -i '/ro.kernel.android.checkjni=0/d' /system/build.prop
busybox sed -i '/ro.config.nocheckin=1/d' /system/build.prop
busybox sed -i '/ro.vold.umsdirtyratio=20/d' /system/build.prop
busybox sed -i '/com.qc.hardware=1/d' /system/build.prop
busybox sed -i '/debug.qc.hardware=true/d' /system/build.prop
busybox sed -i '/debug.qctwa.preservebuf=1/d' /system/build.prop
busybox sed -i '/debug.qctwa.statusbar=1/d' /system/build.prop
	
setprop ro.ril.disable.power.collapse 0
setprop pm.sleep_mode 1
setprop persist.android.strictmode 0
setprop persist.sys.purgeable_assets 1
setprop ro.com.google.networklocation 0
setprop ro.kernel.android.checkjni 0
setprop ro.config.nocheckin 1
setprop ro.vold.umsdirtyratio 20
setprop dalvik.vm.checkjni false
setprop ro.vold.umsdirtyratio int:jit
setprop profiler.force_disable_err_rpt 1
setprop profiler.force_disable_ulog 1
setprop ro.ril.disable.power.collapse 0
setprop pm.sleep_mode 1
setprop ro.com.google.networklocation 0
setprop ro.kernel.android.checkjni 0
setprop ro.config.nocheckin 1
setprop ro.vold.umsdirtyratio 20
setprop com.qc.hardware 1
setprop debug.qc.hardware true
setprop debug.qctwa.preservebuf 1
setprop debug.qctwa.statusbar 1

busybox echo "#Added battery tweaks $(date +%A) at $(date +%H:%M)" >> /data/data/com.androidvip.hebf/hebf_logs/app.log
		
mount -o remount,ro /system		
