#!/system/bin/sh
# HEBF
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

mount -o remount,rw /system

busybox sed -i '/net.tcp.buffersize.default/d' /system/build.prop
busybox sed -i '/net.tcp.buffersize.wifi/d' /system/build.prop
busybox sed -i '/net.tcp.buffersize.lte/d' /system/build.prop
busybox sed -i '/net.tcp.buffersize.hsdpa/d' /system/build.prop
busybox sed -i '/net.tcp.buffersize.hspa/d' /system/build.prop
busybox sed -i '/net.tcp.buffersize.umts/d' /system/build.prop
busybox sed -i '/net.tcp.buffersize.edge/d' /system/build.prop
busybox sed -i '/net.tcp.buffersize.gprs/d' /system/build.prop

setprop net.tcp.buffersize.default 6144,87380,1048576,6144,87380,524288
setprop net.tcp.buffersize.wifi 524288,1048576,2097152,524288,1048576,2097152
setprop net.tcp.buffersize.gprs 6144,87380,1048576,6144,87380,524288
setprop net.tcp.buffersize.edge 6144,87380,524288,6144,16384,262144
setprop net.tcp.buffersize.evdo b=6144,87380,1048576,6144,87380,1048576
setprop net.tcp.buffersize.umts 6144,87380,1048576,6144,87380,524288
setprop net.tcp.buffersize.hspa 6144,87380,524288,6144,16384,262144
setprop net.tcp.buffersize.lte 524288,1048576,2097152,524288,1048576,2097152
setprop net.tcp.buffersize.hsdpa 6144,87380,1048576,6144,87380,1048576

busybox echo "#Added buffer tweaks $(date +%A)  $(date +%H:%M)" >> /data/data/com.androidvip.hebf/hebf_logs/app.log

mount -o remount,ro /system
