#!/system/bin/sh
# HEBF
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

mount -o remount,rw /system
mount -o remount,rw /data/

busybox sed -i '/persist.sys.NV_FPSLIMIT=60/d' /system/build.prop
busybox sed -i '/persist.sys.NV_POWERMODE=1/d' /system/build.prop
busybox sed -i '/persist.sys.NV_PROFVER=15/d' /system/build.prop
busybox sed -i '/persist.sys.NV_STEREOCTRL=0/d' /system/build.prop
busybox sed -i '/persist.sys.NV_STEREOSEPCHG=0/d' /system/build.prop
busybox sed -i '/persist.sys.NV_STEREOSEP=20/d' /system/build.prop
busybox sed -i '/persist.sys.purgeable_assets=1/d' /system/build.prop

rm -f /data/property/persist.sys.NV_FPSLIMIT
rm -f /data/property/persist.sys.NV_POWERMODE
rm -f /data/property/persist.sys.NV_PROFVER
rm -f /data/property/persist.sys.NV_STEREOCTRL
rm -f /data/property/persist.sys.NV_STEREOSEPCHG
rm -f /data/property/persist.sys.NV_STEREOSEP
rm -f /data/property/persist.sys.purgeable_assets

busybox echo "#Removed gamming tweaks $(date +%A), $(date +%H:%M)" >> /data/data/com.androidvip.hebf/hebf_logs/app.log

mount -o remount,ro /system
mount -o remount,ro /data