#!/system/bin/sh
# HEBF
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

mount -o remount,rw /system

# To be removed with the next builds....

busybox sed -i '/net.dns1/d' /system/build.prop
busybox sed -i '/net.dns2/d' /system/build.prop
busybox sed -i '/net.rmnet0.dns1/d' /system/build.prop
busybox sed -i '/net.rmnet0.dns2/d' /system/build.prop
busybox sed -i '/net.ppp0.dns1/d' /system/build.prop
busybox sed -i '/net.ppp0.dns2/d' /system/build.prop
busybox sed -i '/net.wlan0.dns1/d' /system/build.prop
busybox sed -i '/net.wlan0.dns2/d' /system/build.prop
busybox sed -i '/net.gprs.dns1/d' /system/build.prop
busybox sed -i '/net.gprs.dns2/d' /system/build.prop
busybox sed -i '/net.eth0.dns1/d' /system/build.prop
busybox sed -i '/net.eth0.dns2/d' /system/build.prop

busybox echo "#Removed Google DNS $(date +%A) at $(date +%H:%M)" >> /data/data/com.androidvip.hebf/hebf_logs/app.log

mount -o remount,ro /system
