#!/system/bin/sh
# HEBF
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

mount -o remount,rw /
mount -o remount,rw rootfs
mount -o remount,rw /system
clear
sync
 echo "3" > /proc/sys/vm/drop_caches
dc=/proc/sys/vm/drop_caches
dc_v=`cat $dc`
if [ "$dc_v" -gt 1 ]; then
	 echo "1" > /proc/sys/vm/drop_caches
fi
 killall -9 android.process.media
 killall -9 mediaserver

 