#!/system/bin/sh
# HEBF
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

setprop ro.mot.eri.losalert.delay 1000
setprop pm.sleep_mode 1
setprop wifi.supplicant_scan_interval 180
setprop power.saving.mode 1
setprop ro.com.google.networklocation 0
setprop ro.kernel.android.checkjni 0
setprop ro.vold.umsdirtyratio 20
setprop dalvik.vm.checkjni false
setprop dalvik.vm.execution-mode int:jit

busybox echo "[I] |$(date +%Y/%m/%d) $(date +%A), $(date +%H:%M:%S)| Added battery tweaks" >> /data/data/com.androidvip.hebf/hebf_logs/app.log

