#!/system/bin/sh
# HEBF
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

mount -o remount,rw /system

echo "500" > /proc/sys/vm/dirty_expire_centisecs;
echo "1000" > /proc/sys/vm/dirty_writeback_centisecs

busybox sed -i '/#Bateria_KK/d' /system/build.prop
busybox sed -i '/ENFORCE_PROCESS_LIMIT/d' /system/build.prop
busybox sed -i '/MAX_SERVICE_INACTIVITY/d' /system/build.prop
busybox sed -i '/MIN_HIDDEN_APPS/d' /system/build.prop
busybox sed -i '/MAX_HIDDEN_APPS/d' /system/build.prop
busybox sed -i '/CONTENT_APP_IDLE_OFFSET/d' /system/build.prop
busybox sed -i '/EMPTY_APP_IDLE_OFFSET/d' /system/build.prop
busybox sed -i '/MAX_ACTIVITIES/d' /system/build.prop
busybox sed -i '/ACTIVITY_INACTIVITY_RESET_TIME/d' /system/build.prop
busybox sed -i '/MAX_RECENT_TASKS/d' /system/build.prop
busybox sed -i '/MIN_RECENT_TASKS/d' /system/build.prop
busybox sed -i '/APP_SWITCH_DELAY_TIME/d' /system/build.prop
busybox sed -i '/MAX_PROCESSES/d' /system/build.prop
busybox sed -i '/PROC_START_TIMEOUT/d' /system/build.prop
busybox sed -i '/CPU_MIN_CHECK_DURATION/d' /system/build.prop
busybox sed -i '/GC_TIMEOUT/d' /system/build.prop
busybox sed -i '/SERVICE_TIMEOUT/d' /system/build.prop
busybox sed -i '/MIN_CRASH_INTERVAL/d' /system/build.prop
busybox sed -i '/Bateria_KK/d' /system/build.prop
busybox sed -i '/ENFORCE_PROCESS_LIMIT=false/d' /system/build.prop
busybox sed -i '/MAX_SERVICE_INACTIVITY=false/d' /system/build.prop
busybox sed -i '/MIN_HIDDEN_APPS=false/d' /system/build.prop
busybox sed -i '/MAX_HIDDEN_APPS=false/d' /system/build.prop
busybox sed -i '/CONTENT_APP_IDLE_OFFSET=false/d' /system/build.prop
busybox sed -i '/EMPTY_APP_IDLE_OFFSET=false/d' /system/build.prop
busybox sed -i '/MAX_ACTIVITIES=false/d' /system/build.prop
busybox sed -i '/ACTIVITY_INACTIVITY_RESET_TIME=false/d' /system/build.prop
busybox sed -i '/MAX_RECENT_TASKS=false/d' /system/build.prop
busybox sed -i '/MIN_RECENT_TASKS=false/d' /system/build.prop
busybox sed -i '/APP_SWITCH_DELAY_TIME=false/d' /system/build.prop
busybox sed -i '/MAX_PROCESSES=false/d' /system/build.prop
busybox sed -i '/PROC_START_TIMEOUT=false/d' /system/build.prop
busybox sed -i '/CPU_MIN_CHECK_DURATION=false/d' /system/build.prop
busybox sed -i '/GC_TIMEOUT=false/d' /system/build.prop
busybox sed -i '/SERVICE_TIMEOUT=false/d' /system/build.prop
busybox sed -i '/MIN_CRASH_INTERVAL=false/d' /system/build.prop
busybox sed -i '/ro.ril.disable.power.collapse=0/d' /system/build.prop
busybox sed -i '/pm.sleep_mode=1/d' /system/build.prop
busybox sed -i '/persist.android.strictmode=0/d' /system/build.prop
busybox sed -i '/persist.sys.purgeable_assets=1/d' /system/build.prop
busybox sed -i '/ro.com.google.networklocation=0/d' /system/build.prop
busybox sed -i '/ro.kernel.android.checkjni=0/d' /system/build.prop
busybox sed -i '/ro.config.nocheckin=1/d' /system/build.prop
busybox sed -i '/ro.vold.umsdirtyratio=20/d' /system/build.prop
busybox sed -i '/dalvik.vm.checkjni=false/d' /system/build.prop
busybox sed -i '/ro.vold.umsdirtyratio=int:jit/d' /system/build.prop
busybox sed -i '/profiler.force_disable_err_rpt=1/d' /system/build.prop
busybox sed -i '/profiler.force_disable_ulog=1/d' /system/build.prop
busybox sed -i '/ro.ril.disable.power.collapse=0/d' /system/build.prop
busybox sed -i '/pm.sleep_mode=1/d' /system/build.prop
busybox sed -i '/persist.android.strictpersist.sys.pur/d' /system/build.propgeable_assets=1
busybox sed -i '/ro.com.google.networklocation=0/d' /system/build.prop
busybox sed -i '/ro.kernel.android.checkjni=0/d' /system/build.prop
busybox sed -i '/ro.config.nocheckin=1/d' /system/build.prop
busybox sed -i '/ro.vold.umsdirtyratio=20/d' /system/build.prop
busybox sed -i '/dalvik.vm.checkjni=false/d' /system/build.prop
busybox sed -i '/dalvik.vm.execution-mode=int:jit/d' /system/build.prop
busybox sed -i '/profiler.force_disable_err_rpt=1/d' /system/build.prop
busybox sed -i '/profiler.force_disable_ulog=1/d' /system/build.prop
busybox sed -i '/pm.sleep_mode=1/d' /system/build.prop
busybox sed -i '/ro.ril.power_collapse=1/d' /system/build.prop
busybox sed -i '/wifi.supplicant_scan_interval=180/d' /system/build.prop
busybox sed -i '/ro.mot.eri.losalert.delay=1000/d' /system/build.prop
busybox sed -i '/ro.mot.eri.losalert.delay=1000/d' /system/build.prop
busybox sed -i '/com.qc.hardware=1/d' /system/build.prop
busybox sed -i '/debug.qc.hardware=true/d' /system/build.prop
busybox sed -i '/debug.qctwa.preservebuf=1/d' /system/build.prop
busybox sed -i '/debug.qctwa.statusbar=1/d' /system/build.prop

#Adicionar		
 echo "#Bateria_KK
ENFORCE_PROCESS_LIMIT=false
MAX_SERVICE_INACTIVITY=false
MIN_HIDDEN_APPS=false
MAX_HIDDEN_APPS=false
CONTENT_APP_IDLE_OFFSET=false
EMPTY_APP_IDLE_OFFSET=false
MAX_ACTIVITIES=false
ACTIVITY_INACTIVITY_RESET_TIME=false
MAX_RECENT_TASKS=false
MIN_RECENT_TASKS=false
APP_SWITCH_DELAY_TIME=false
MAX_PROCESSES=false
PROC_START_TIMEOUT=false
CPU_MIN_CHECK_DURATION=false
GC_TIMEOUT=false
SERVICE_TIMEOUT=false
MIN_CRASH_INTERVAL=false
ro.ril.disable.power.collapse=0
pm.sleep_mode=1
persist.android.strictmode=0
persist.sys.purgeable_assets=1
ro.com.google.networklocation=0
ro.kernel.android.checkjni=0
ro.config.nocheckin=1
ro.vold.umsdirtyratio=20
dalvik.vm.checkjni=false
ro.vold.umsdirtyratio=int:jit
profiler.force_disable_err_rpt=1
profiler.force_disable_ulog=1
ro.ril.disable.power.collapse=0
pm.sleep_mode=1
persist.android.strictpersist.sys.purgeable_assets=1
ro.com.google.networklocation=0
ro.kernel.android.checkjni=0
ro.config.nocheckin=1
ro.vold.umsdirtyratio=20
dalvik.vm.checkjni=false
dalvik.vm.execution-mode=int:jit
profiler.force_disable_err_rpt=1
profiler.force_disable_ulog=1
pm.sleep_mode=1
ro.ril.power_collapse=1
wifi.supplicant_scan_interval=180
ro.mot.eri.losalert.delay=1000
ro.mot.eri.losalert.delay=1000
com.qc.hardware=1
debug.qc.hardware=true
debug.qctwa.preservebuf=1
debug.qctwa.statusbar=1
" >> /system/build.prop
busybox sed -i '/^$/d' /system/build.prop
		
mount -o remount,ro /system		
