#!/system/bin/sh
# HEBF
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

mount -o remount,rw /system

busybox sed -i '/#Bateria_LP/d' /system/build.prop
busybox sed -i '/ro.mot.eri.losalert.delay=1000/d' /system/build.prop
busybox sed -i '/ro.ril.power_collapse=1/d' /system/build.prop
busybox sed -i '/pm.sleep_mode=1/d' /system/build.prop
busybox sed -i '/wifi.supplicant_scan_interval=180/d' /system/build.prop
busybox sed -i '/power.saving.mode=1/d' /system/build.prop
busybox sed -i '/ro.com.google.networklocation=0/d' /system/build.prop
busybox sed -i '/ro.kernel.android.checkjni=0/d' /system/build.prop
busybox sed -i '/ro.config.nocheckin=1/d' /system/build.prop
busybox sed -i '/ro.vold.umsdirtyratio=20/d' /system/build.prop
busybox sed -i '/dalvik.vm.checkjni=false/d' /system/build.prop
busybox sed -i '/dalvik.vm.execution-mode=int:jit/d' /system/build.prop
busybox sed -i '/profiler.force_disable_err_rpt=1/d' /system/build.prop

mount -o remount,ro /system
