#!/system/bin/sh
# HEBF
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

mount -o remount,rw /system

busybox sed -i '/net.tcp.buffersize.default/d' /system/build.prop
busybox sed -i '/net.tcp.buffersize.wifi/d' /system/build.prop
busybox sed -i '/net.tcp.buffersize.lte/d' /system/build.prop
busybox sed -i '/net.tcp.buffersize.hsdpa/d' /system/build.prop
busybox sed -i '/net.tcp.buffersize.hspa/d' /system/build.prop
busybox sed -i '/net.tcp.buffersize.umts/d' /system/build.prop
busybox sed -i '/net.tcp.buffersize.edge/d' /system/build.prop
busybox sed -i '/net.tcp.buffersize.gprs/d' /system/build.prop

busybox echo "net.tcp.buffersize.default=4096,87380,256960,4096, 16384,256960
net.tcp.buffersize.wifi=4096,87380,256960,4096,163 84,256960
net.tcp.buffersize.lte=524288,1048576,2097152,5242 88,1048576,2097152
net.tcp.buffersize.hsdpa=6144,87380,1048576,6144,8 7380,1048576
net.tcp.buffersize.hspa=6144,87380,524288,6144,163 84,262144
net.tcp.buffersize.umts=4096,87380,256960,4096,163 84,256960
net.tcp.buffersize.edge=4096,87380,256960,4096,163 84,256960
net.tcp.buffersize.gprs=4096,87380,256960,4096,163 84,256960
" >> /system/build.prop

busybox echo "#Added buffer tweaks $(date +%A) at $(date +%H:%M)" >> /system/etc/HEBF/app.log

mount -o remount,ro /system
