#!/system/bin/sh
# HEBF
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

NIVEL=$(cat /sys/class/power_supply/battery/capacity)
mount -o rw,remount /data

	if [ "$NIVEL" == "100" ] ; then
		 mount -o rw,remount /data
		 rm -f /data/system/batterystats.bin
		 busybox echo "[I] |$(date +%Y/%m/%d) $(date +%A), $(date +%H:%M)| Battery calibrated" >> /data/data/com.androidvip.hebf/hebf_logs/app.log
		 mount -o ro,remount /data
	else
		 busybox echo "[E] |$(date +%Y/%m/%d) $(date +%A), $(date +%H:%M)| [ERROR:] Battery is not fully charged" >> /data/data/com.androidvip.hebf/hebf_logs/app.log
	fi
fi
mount -o ro,remount /data