#!/system/bin/sh
# HEBF
# Credits to: Paget96 and CALIBAN666
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

mount -o remount,rw /data

rm -f /cache/*.apk 2> /dev/null
rm -f /cache/*.tmp 2> /dev/null
rm -f /cache/recovery/* 2> /dev/null
rm -f /data/*.log 2> /dev/null
rm -f /data/*.txt 2> /dev/null
rm -f /data/anr/*.* 2> /dev/null
rm -f /data/backup/pending/*.tmp 2> /dev/null
rm -f /data/cache/*.* 2> /dev/null
rm -f /data/dalvik-cache/*.apk 2> /dev/null
rm -f /data/dalvik-cache/*.tmp 2> /dev/null
rm -f /data/log/*.* 2> /dev/null
rm -f /data/local/*.apk 2> /dev/null
rm -f /data/local/*.log 2> /dev/null
rm -f /data/local/tmp/*.* 2> /dev/null
rm -f /data/tombstones/* 2> /dev/null
rm -f /data/system/dropbox/* 2> /dev/null
rm -f /data/system/usagestats/* 2> /dev/null

busybox echo "[I] |$(date +%Y/%m/%d) $(date +%A), $(date +%H:%M:%S)| Junk cleaned" >> /data/data/com.androidvip.hebf/hebf_logs/app.log

mount -o ro,remount /data