#!/system/bin/sh
# HEBF
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

mount -o remount,rw /system

busybox sed -i '/persist.sys.NV_FPSLIMIT=60/d' /system/build.prop
busybox sed -i '/persist.sys.NV_POWERMODE=1/d' /system/build.prop
busybox sed -i '/persist.sys.NV_PROFVER=15/d' /system/build.prop
busybox sed -i '/persist.sys.NV_STEREOCTRL=0/d' /system/build.prop
busybox sed -i '/persist.sys.NV_STEREOSEPCHG=0/d' /system/build.prop
busybox sed -i '/persist.sys.NV_STEREOSEP=20/d' /system/build.prop
busybox sed -i '/persist.sys.purgeable_assets=1/d' /system/build.prop

setprop persist.sys.NV_FPSLIMIT 60 
setprop persist.sys.NV_POWERMODE 1
setprop persist.sys.NV_PROFVER 15
setprop persist.sys.NV_STEREOCTRL 0
setprop persist.sys.NV_STEREOSEPCHG 0
setprop persist.sys.NV_STEREOSEP 20
setprop persist.sys.purgeable_assets 1

echo "#Modo jogo
persist.sys.NV_FPSLIMIT=60 
persist.sys.NV_POWERMODE=1 
persist.sys.NV_PROFVER=15 
persist.sys.NV_STEREOCTRL=0 
persist.sys.NV_STEREOSEPCHG=0 
persist.sys.NV_STEREOSEP=20 
persist.sys.purgeable_assets=1
" >> /system/build.prop

busybox echo "#Added gamming tweaks $(date +%A) at $(date +%H:%M)" >> /system/etc/HEBF/app.log

mount -o remount,ro /system
