#!/system/bin/sh
# HEBF
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

mount -o remount,rw /system

busybox sed -i '/net.dns1/d' /system/build.prop
busybox sed -i '/net.dns2/d' /system/build.prop
busybox sed -i '/net.rmnet0.dns1/d' /system/build.prop
busybox sed -i '/net.rmnet0.dns2/d' /system/build.prop
busybox sed -i '/net.ppp0.dns1/d' /system/build.prop
busybox sed -i '/net.ppp0.dns2/d' /system/build.prop
busybox sed -i '/net.wlan0.dns1/d' /system/build.prop
busybox sed -i '/net.wlan0.dns2/d' /system/build.prop
busybox sed -i '/net.gprs.dns1/d' /system/build.prop
busybox sed -i '/net.gprs.dns2/d' /system/build.prop
busybox sed -i '/net.eth0.dns1/d' /system/build.prop
busybox sed -i '/net.eth0.dns2/d' /system/build.prop

busybox echo "net.dns1=8.8.8.8
net.dns2=8.8.4.4
net.rmnet0.dns1=8.8.8.8
net.rmnet0.dns2=8.8.4.4
net.gprs.dns1=8.8.8.8
net.gprs.dns2=8.8.4.4
net.ppp0.dns1=8.8.8.8
net.ppp0.dns2=8.8.4.4
net.wlan0.dns1=8.8.8.8
net.wlan0.dns2=8.8.4.4
net.eth0.dns1=8.8.8.8
net.eth0.dns2=8.8.4.4
" >> /system/build.prop

busybox echo "#Added Google DNS $(date +%A) at $(date +%H:%M)" >> /system/etc/HEBF/app.log

mount -o remount,ro /system
