#!/system/bin/sh
# HEBF
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

mount -o remount,rw /system

busybox sed -i '/hw3d.force=1/d' /system/build.prop
busybox sed -i '/ro.product.gpu.driver=1/d' /system/build.prop
busybox sed -i '/persist.sampling_profiler=0/d' /system/build.prop
busybox sed -i '/hwui.render_dirty_regions=false/d' /system/build.prop
busybox sed -i '/persist.sampling_profiler=0/d' /system/build.prop
busybox sed -i '/persist.sys.ui.hw=1/d' /system/build.prop
busybox sed -i '/ro.config.disable.hw_accel=false/d' /system/build.prop
busybox sed -i '/video.accelerate.hw=1/d' /system/build.prop
busybox sed -i '/persist.sys.composition.type=gpu/d' /system/build.prop
busybox sed -i '/debug.egl.profiler=1/d' /system/build.prop
busybox sed -i '/debug.egl.hw=1' /system/build.prop
busybox sed -i '/debug.composition.type=gpu/d' /system/build.prop
busybox sed -i '/ro.vold.umsdirtyratio=20/d' /system/build.prop
busybox sed -i '/hwui.disable_vsync=true/d' /system/build.prop

setprop persist.sampling_profiler 0
setprop persist.sys.ui.hw 1
setprop persist.sys.composition.type gpu

busybox echo "hw3d.force=1
ro.product.gpu.driver=1
persist.sampling_profiler=0
hwui.render_dirty_regions=false
persist.sampling_profiler=0
persist.sys.ui.hw=1
ro.config.disable.hw_accel=false
video.accelerate.hw=1
persist.sys.composition.type=gpu
debug.egl.profiler=1
debug.egl.hw=1
debug.composition.type=gpu
ro.vold.umsdirtyratio=20
hwui.disable_vsync=true
" >> /system/build.prop

busybox echo "#Added GPU tweaks $(date +%A) at $(date +%H:%M)" >> /system/etc/HEBF/app.log

mount -o remount,ro /system
