#!/system/bin/sh
# HEBF
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

mount -o remount,rw /system
mount -o remount,rw /data

busybox sed -i '/hw3d.force=1/d' /system/build.prop
busybox sed -i '/ro.product.gpu.driver=1/d' /system/build.prop
busybox sed -i '/persist.sampling_profiler=0/d' /system/build.prop
busybox sed -i '/hwui.render_dirty_regions=false/d' /system/build.prop
busybox sed -i '/persist.sampling_profiler=0/d' /system/build.prop
busybox sed -i '/persist.sys.ui.hw=1/d' /system/build.prop
busybox sed -i '/ro.config.disable.hw_accel=false/d' /system/build.prop
busybox sed -i '/video.accelerate.hw=1/d' /system/build.prop
busybox sed -i '/persist.sys.composition.type=gpu/d' /system/build.prop
busybox sed -i '/debug.egl.profiler=1/d' /system/build.prop
busybox sed -i '/debug.egl.hw=1' /system/build.prop
busybox sed -i '/debug.composition.type=gpu/d' /system/build.prop
busybox sed -i '/ro.vold.umsdirtyratio=20/d' /system/build.prop

rm -f /data/property/persist.sampling_profiler
rm -f /data/property/persist.sys.ui.hw
rm -f /data/property/persist.sys.composition.type

busybox echo "#Removed GPU tweaks $(date +%A) at $(date +%H:%M)" >> /system/etc/HEBF/app.log

mount -o remount,ro /system
mount -o remount,ro /data
