#!/system/bin/sh
# HEBF
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

setprop hw3d.force 1
setprop ro.product.gpu.driver 1
setprop persist.sampling_profiler 0
setprop hwui.render_dirty_regions false
setprop persist.sampling_profiler 0
setprop persist.sys.ui.hw 1
setprop ro.config.disable.hw_accel false
setprop video.accelerate.hw 1
setprop persist.sys.composition.type gpu
setprop debug.egl.profiler 1
setprop debug.egl.hw 1
setprop debug.composition.type gpu
setprop ro.vold.umsdirtyratio 20
setprop hwui.disable_vsync true
