#!/system/bin/sh
# HEBF
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

# じゃあね、よろしく。

mount -o remount,rw /data

busybox sed -i '/sys.keep_app_1=/d' /data/local.prop
rm -f /data/property/persist.sampling_profiler
rm -f /data/property/persist.sys.ui.hw
rm -f /data/property/persist.sys.composition.type
rm -f /data/property/persist.sys.use_16bpp_alpha
rm -f /data/property/persist.sys.NV_FPSLIMIT
rm -f /data/property/persist.sys.NV_POWERMODE
rm -f /data/property/persist.sys.NV_PROFVER
rm -f /data/property/persist.sys.NV_STEREOCTRL
rm -f /data/property/persist.sys.NV_STEREOSEPCHG
rm -f /data/property/persist.sys.NV_STEREOSEP
rm -f /data/property/persist.sys.purgeable_assets
rm -f /data/property/persist.service.pcsync.enable
rm -f /data/property/persist.service.lgospd.enable
rm -f /data/property/persist.sys.shutdown.mode
rm -f /data/property/persist.sampling_profiler
rm -f /data/property/persist.sys.ui.hw
rm -f /data/property/persist.sys.composition.type

mount -o remount,ro /data

start logd
busybox echo "0" > /sys/devices/system/cpu/sched_mc_power_savings
setprop ro.config.low_ram false
setprop debug.egl.swapinterval 1

mount -o remount,rw /system

rf -rf /system/etc/HEBF
busybox sed -i '/ro.config.hw_power_saving=1/d' /system/build.prop
busybox sed -i '/ro.com.google.networklocation=0/d' /system/build.prop
busybox sed -i '/ro.mot.eri.losalert.delay=1000/d' /system/build.prop
busybox sed -i '/ro.ril.power_collapse=1/d' /system/build.prop
busybox sed -i '/pm.sleep_mode=1/d' /system/build.prop
busybox sed -i '/wifi.supplicant_scan_interval=180/d' /system/build.prop
busybox sed -i '/power.saving.mode=1/d' /system/build.prop
busybox sed -i '/ro.kernel.android.checkjni=0/d' /system/build.prop
busybox sed -i '/ro.config.nocheckin=1/d' /system/build.prop
busybox sed -i '/ro.vold.umsdirtyratio=20/d' /system/build.prop
busybox sed -i '/dalvik.vm.checkjni=false/d' /system/build.prop
busybox sed -i '/dalvik.vm.execution-mode=int:jit/d' /system/build.prop
busybox sed -i '/profiler.force_disable_err_rpt=1/d' /system/build.prop
busybox sed -i '/hw3d.force=1/d' /system/build.prop
busybox sed -i '/ro.product.gpu.driver=1/d' /system/build.prop
busybox sed -i '/persist.sampling_profiler=0/d' /system/build.prop
busybox sed -i '/hwui.render_dirty_regions=false/d' /system/build.prop
busybox sed -i '/persist.sampling_profiler=0/d' /system/build.prop
busybox sed -i '/persist.sys.ui.hw=1/d' /system/build.prop
busybox sed -i '/ro.config.disable.hw_accel=false/d' /system/build.prop
busybox sed -i '/video.accelerate.hw=1/d' /system/build.prop
busybox sed -i '/persist.sys.composition.type=gpu/d' /system/build.prop
busybox sed -i '/debug.egl.profiler=1/d' /system/build.prop
busybox sed -i '/debug.egl.hw=1/d' /system/build.prop
busybox sed -i '/debug.composition.type=gpu/d' /system/build.prop
busybox sed -i '/ro.vold.umsdirtyratio=20/d' /system/build.prop
busybox sed -i '/hwui.disable_vsync=true/d' /system/build.prop
busybox sed -i '/debug.composition.type=c2d/d' /system/build.prop
busybox sed -i '/persist.sys.composition.type=c2d/d' /system/build.prop
busybox sed -i '/debug.enabletr=true/d' /system/build.prop
busybox sed -i '/debug.overlayui.enable=1/d' /system/build.prop
busybox sed -i '/debug.qctwa.preservebuf=1/d' /system/build.prop
busybox sed -i '/dev.pm.dyn_samplingrate=1/d' /system/build.prop
busybox sed -i '/ro.fb.mode=1/d' /system/build.prop
busybox sed -i '/ro.sf.compbypass.enable=0/d' /system/build.prop
busybox sed -i '/ro.vold.umsdirtyratio=20/d' /system/build.prop
busybox sed -i '/debug.performance.tuning=1/d' /system/build.prop
busybox sed -i '/persist.sys.use_dithering=0/d' /system/build.prop
busybox sed -i '/ro.min.fling_velocity=8000/d' /system/build.prop
busybox sed -i '/persist.sys.use_16bpp_alpha=1/d' /system/build.prop
busybox sed -i '/ro.mot.eri.losalert.delay=1000/d' /system/build.prop
busybox sed -i '/persist.sys.NV_FPSLIMIT=60/d' /system/build.prop
busybox sed -i '/persist.sys.NV_POWERMODE=1/d' /system/build.prop
busybox sed -i '/persist.sys.NV_PROFVER=15/d' /system/build.prop
busybox sed -i '/persist.sys.NV_STEREOCTRL=0/d' /system/build.prop
busybox sed -i '/persist.sys.NV_STEREOSEPCHG=0/d' /system/build.prop
busybox sed -i '/persist.sys.NV_STEREOSEP=20/d' /system/build.prop
busybox sed -i '/persist.sys.purgeable_assets=1/d' /system/build.prop
busybox sed -i '/ro.min_pointer_dur=8/d' /system/build.prop
busybox sed -i '/ro.max.fling_velocity=12000/d' /system/build.prop
busybox sed -i '/persist.sys.scrollingcache=3' /system/build.prop
busybox sed -i '/ro.securestorage.knox=false/d' /system/build.prop
busybox sed -i '/ro.min.fling_velocity=8000' /system/build.prop
busybox sed -i '/windowsmgr.max_events_per_sec=*/d' /system/build.prop
busybox sed -i '/persist.service.lgospd.enable=0/d' /system/build.prop
busybox sed -i '/persist.service.pcsync.enable=0/d' /system/build.prop
busybox sed -i '/touch.pressure.scale=0.001/d' /system/build.prop
busybox sed -i '/ro.config.low_ram=/d' /system/build.prop
busybox sed -i '/debug.egl.swapinterval=-60/d' /system/build.prop
busybox sed -i '/ro.telephony.call_ring.delay=0/d' /system/build.prop
busybox sed -i '/ro.config.hw_quickpoweron=true/d' /system/build.prop
busybox sed -i '/persist.sys.shutdown.mode=hibernate/d' /system/build.prop
busybox sed -i '/debug.sf.nobootanimation=.*/d' /system/build.prop
busybox sed -i '/captive_portal_detection_enabled=/d' /system/build.prop
busybox sed -i '/net.dns1/d' /system/build.prop
busybox sed -i '/net.dns2/d' /system/build.prop
busybox sed -i '/net.rmnet0.dns1/d' /system/build.prop
busybox sed -i '/net.rmnet0.dns2/d' /system/build.prop
busybox sed -i '/net.ppp0.dns1/d' /system/build.prop
busybox sed -i '/net.ppp0.dns2/d' /system/build.prop
busybox sed -i '/net.wlan0.dns1/d' /system/build.prop
busybox sed -i '/net.wlan0.dns2/d' /system/build.prop
busybox sed -i '/net.gprs.dns1/d' /system/build.prop
busybox sed -i '/net.gprs.dns2/d' /system/build.prop
busybox sed -i '/net.eth0.dns1/d' /system/build.prop
busybox sed -i '/net.eth0.dns2/d' /system/build.prop
busybox sed -i '/ro.ril.hsxpa=2/d' /system/build.prop
busybox sed -i '/ro.ril.hep=1/d' /system/build.prop
busybox sed -i '/ro.ril.enable.dtm=1/d' /system/build.prop
busybox sed -i '/ro.ril.hsdpa.category=10/d' /system/build.prop
busybox sed -i '/ro.ril.enable.a53=1/d' /system/build.prop
busybox sed -i '/ro.ril.enable.3g.prefix=1/d' /system/build.prop
busybox sed -i '/ro.ril.gprsclass=10/d' /system/build.prop
busybox sed -i '/ro.ril.hsupa.category=7/d' /system/build.prop
busybox sed -i '/ro.ril.hsdpa.category=10/d' /system/build.prop
busybox sed -i '/ro.ril.enable.a52=1/d' /system/build.prop
busybox sed -i '/ro.ril.set.mtu1472=1/d' /system/build.prop
busybox sed -i '/persist.cust.tel.eons=1/d' /system/build.prop
busybox sed -i '/net.tcp.buffersize.default/d' /system/build.prop
busybox sed -i '/net.tcp.buffersize.wifi/d' /system/build.prop
busybox sed -i '/net.tcp.buffersize.lte/d' /system/build.prop
busybox sed -i '/net.tcp.buffersize.hsdpa/d' /system/build.prop
busybox sed -i '/net.tcp.buffersize.hspa/d' /system/build.prop
busybox sed -i '/net.tcp.buffersize.umts/d' /system/build.prop
busybox sed -i '/net.tcp.buffersize.edge/d' /system/build.prop
busybox sed -i '/net.tcp.buffersize.gprs/d' /system/build.prop
busybox sed -i '/media.stagefright.enable-http=true/d' /system/build.prop
busybox sed -i '/media.stagefright.enable-player=true/d' /system/build.prop
busybox sed -i '/media.stagefright.enable-meta=true/d' /system/build.prop
busybox sed -i '/media.stagefright.enable-aac=true/d' /system/build.prop
busybox sed -i '/media.stagefright.enable-qcp=true/d' /system/build.prop
busybox sed -i '/media.stagefright.enable-scan=tru/d' /system/build.prop
busybox sed -i '/media.stagefright.enable-record=true/d' /system/build.prop
rm -f /system/etc/init.d/02play
rm -f /system/etc/init.d/08wifi
rm -f /system/etc/init.d/09yrolram
rm -f /system/etc/init.d/03zipalign
rm -f /system/etc/init.d/04tcp

mount -o remount,ro /system
