#!/system/bin/sh
# HEBF
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

mount -o remount,rw /system

HEBF=/system/etc/HEBF/kill_media.log
 rm -f $HEBF
 touch $HEBF

 echo "# HEBF_Media" | busybox tee -a $HEBF
 echo "" | busybox tee -a $HEBF
 echo "Killing media server" | busybox tee -a $HEBF

if [ "`pgrep media`" ] && [ "`pgrep mediaserver`" ]; then
	 killall -9 android.process.media
	 killall -9 mediaserver
fi

 echo "" | busybox tee -a $HEBF
 echo "OK!" | busybox tee -a $HEBF

mount -o remount,ro /system
