#!/system/bin/sh
# HEBF
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

mount -o remount,rw /system

busybox sed -i '/#Liquid Smooth UI/d' /system/build.prop
busybox sed -i '/persist.service.lgospd.enable=0/d' /system/build.prop
busybox sed -i '/persist.service.pcsync.enable=0/d' /system/build.prop
busybox sed -i '/touch.pressure.scale=0.003/d' /system/build.prop

busybox echo "#Liquid Smooth UI
persist.service.lgospd.enable=0
persist.service.pcsync.enable=0
touch.pressure.scale=0.003
" >> /system/build.prop

mount -o remount,ro /system
