#!/system/bin/sh
# HEBF
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

mount -o remount,rw /system
mount -o remount,rw /data

busybox sed -i '/persist.service.lgospd.enable=0/d' /system/build.prop
busybox sed -i '/persist.service.pcsync.enable=0/d' /system/build.prop
busybox sed -i '/touch.pressure.scale=0.001/d' /system/build.prop

rm -f /data/property/persist.service.pcsync.enable
rm -f /data/property/persist.service.lgospd.enable

busybox echo "|$(date +%Y/%m/%d) $(date +%A), $(date +%H:%M)| Removed UI tweaks" >> /data/data/com.androidvip.hebf/hebf_logs/app.log

mount -o remount,ro /system
mount -o remount,ro /data
