#!/system/bin/sh
# HEBF
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

busybox echo "0" > /proc/sys/net/ipv4/tcp_timestamps
busybox echo "1" > /proc/sys/net/ipv4/tcp_tw_reuse
busybox echo "1" > /proc/sys/net/ipv4/tcp_sack
busybox echo "1" > /proc/sys/net/ipv4/tcp_dsack
busybox echo "1" > /proc/sys/net/ipv4/tcp_tw_recycle
busybox echo "1" > /proc/sys/net/ipv4/tcp_window_scaling
busybox echo "1" > /proc/sys/net/ipv4/tcp_moderate_rcvbuf
busybox echo "1" > /proc/sys/net/ipv4/icmp_echo_ignore_broadcasts
busybox echo "1" > /proc/sys/net/ipv4/icmp_echo_ignore_all
busybox echo "1" > /proc/sys/net/ipv4/icmp_ignore_bogus_error_responses
busybox echo "5" > /proc/sys/net/ipv4/tcp_keepalive_probes
busybox echo "30" > /proc/sys/net/ipv4/tcp_keepalive_intvl
busybox echo "30" > /proc/sys/net/ipv4/tcp_fin_timeout
