#!/system/bin/sh
# HEBF
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

mount -o remount,rw /system

busybox sed -i '/#Performance/d' /system/build.prop
busybox sed -i '/logcat.live=disable/d' /system/build.prop
busybox sed -i '/debug.enabletr=true/d' /system/build.prop
busybox sed -i '/dev.pm.dyn_samplingrate=1/d' /system/build.prop
busybox sed -i '/video.accelerate.hw=1/d' /system/build.prop
busybox sed -i '/ro.vold.umsdirtyratio=20/d' /system/build.prop
busybox sed -i '/debug.overlayui.enable=1/d' /system/build.prop
busybox sed -i '/debug.egl.hw=1/d' /system/build.prop
busybox sed -i '/ro.fb.mode=1/d' /system/build.prop
busybox sed -i '/hw3d.force=1/d' /system/build.prop
busybox sed -i '/persist.sys.ui.hw=1/d' /system/build.prop
busybox sed -i '/ro.sf.compbypass.enable=0/d' /system/build.prop
busybox sed -i '/debug.sf.hw=1/d' /system/build.prop
busybox sed -i '/debug.composition.type=c2d/d' /system/build.prop
busybox sed -i '/debug.performance.tuning=1/d' /system/build.prop

setprop persist.sys.ui.hw 1

busybox echo "#Performance
logcat.live=disable
debug.enabletr=true
dev.pm.dyn_samplingrate=1
video.accelerate.hw=1
ro.vold.umsdirtyratio=20
debug.overlayui.enable=1
debug.egl.hw=1
ro.fb.mode=1
hw3d.force=1
persist.sys.ui.hw=1
ro.sf.compbypass.enable=0
debug.sf.hw=1
debug.composition.type=c2d
debug.performance.tuning=1
" >> /system/build.prop

mount -o remount,ro /system
