#!/system/bin/sh
# HEBF
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#
mount -o rw,remount /system

busybox echo "su -c pm disable com.google.android.gms/com.google.android.location.settings.GoogleLocationSettingsActivity" >> /system/etc/init.d/02play
busybox echo "su -c pm disable com.google.android.gms/com.google.android.location.settings.LocationHistorySettingsActivity" >> /system/etc/init.d/02play
busybox echo "su -c pm disable com.google.android.gms/com.google.android.location.settings.LocationSettingsCheckerActivity" >> /system/etc/init.d/02play
busybox echo "su -c pm disable com.google.android.gms/com.google.android.location.reporting.service.ReportingContentProvider" >> /system/etc/init.d/02play
busybox echo "su -c pm disable com.google.android.gms/com.google.android.location.internal.LocationContentProvider" >> /system/etc/init.d/02play
busybox echo "su -c pm disable com.google.android.gms/com.google.android.location.internal.LocationProviderEnabler" >> /system/etc/init.d/02play
busybox echo "su -c pm disable com.google.android.gms/com.google.android.location.places.ImplicitSignalsReceiver" >> /system/etc/init.d/02play
busybox echo "su -c pm disable com.google.android.gms/com.google.android.location.reporting.service.DeleteHistoryService" >> /system/etc/init.d/02play
busybox echo "su -c pm disable com.google.android.gms/com.google.android.location.reporting.service.LocationHistoryInjectorService" >> /system/etc/init.d/02play
busybox echo "su -c pm disable com.google.android.gms/com.google.android.location.reporting.service.ReportingAndroidService" >> /system/etc/init.d/02play
busybox echo "su -c pm disable com.google.android.gms/com.google.android.location.reporting.service.ReportingSyncService" >> /system/etc/init.d/02play
busybox echo "su -c pm disable com.google.android.gms/com.google.android.location.fused.FusedLocationService" >> /system/etc/init.d/02play
busybox echo "su -c pm disable com.google.android.gms/com.google.android.location.fused.service.FusedProviderService" >> /system/etc/init.d/02play
busybox echo "su -c pm disable com.google.android.gms/com.google.android.location.places.PlaylogService" >> /system/etc/init.d/02play

mount -o ro,remount /system
