#!/system/bin/sh
# HEBF
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

mount -o remount,rw /system

busybox sed -i '/debug.composition.type=c2d/d' /system/build.prop
busybox sed -i '/persist.sys.composition.type=c2d/d' /system/build.prop
busybox sed -i '/debug.enabletr=true/d' /system/build.prop
busybox sed -i '/debug.overlayui.enable=1/d' /system/build.prop
busybox sed -i '/debug.qctwa.preservebuf=1/d' /system/build.prop
busybox sed -i '/dev.pm.dyn_samplingrate=1/d' /system/build.prop
busybox sed -i '/ro.fb.mode=1/d' /system/build.prop
busybox sed -i '/ro.sf.compbypass.enable=0/d' /system/build.prop
busybox sed -i '/ro.vold.umsdirtyratio=20/d' /system/build.prop

busybox echo "|$(date +%Y/%m/%d) $(date +%A), $(date +%H:%M)| Removed rendering tweaks" >> /data/data/com.androidvip.hebf/hebf_logs/app.log

mount -o remount,ro /system
