#!/system/bin/sh
# HEBF
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

setprop windowsmgr.max_events_per_sec 200
setprop ro.min_pointer_dur 8
setprop persist.sys.scrollingcache 3
setprop ro.securestorage.knox false
setprop ro.max.fling_velocity 12000
setprop ro.min.fling_velocity 8000

busybox echo "[I] |$(date +%Y/%m/%d) $(date +%A), $(date +%H:%M:%S)| Scrolling tweaks added" >> /data/data/com.androidvip.hebf/hebf_logs/app.log
