#!/system/bin/sh
# HEBF
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

mount -o remount,rw /system

busybox sed -i '/media.stagefright.enable-http=true/d' /system/build.prop
busybox sed -i '/media.stagefright.enable-player=true/d' /system/build.prop
busybox sed -i '/media.stagefright.enable-meta=true/d' /system/build.prop
busybox sed -i '/media.stagefright.enable-aac=true/d' /system/build.prop
busybox sed -i '/media.stagefright.enable-qcp=true/d' /system/build.prop
busybox sed -i '/media.stagefright.enable-scan=tru/d' /system/build.prop
busybox sed -i '/media.stagefright.enable-record=true/d' /system/build.prop

busybox echo "#Removed video streaming tweaks $(date +%A) at $(date +%H:%M)" >> /system/etc/HEBF/app.log

mount -o remount,ro /system
