#!/system/bin/sh
# HEBF
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

mount -o rw,remount /system

busybox touch /system/etc/init.d/00thumb

echo "#!/system/bin/sh
# HEBF
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#" > /system/etc/init.d/00thumb
echo "" >> /system/etc/init.d/00thumb
echo "mount -o rw,remount /data" >> /system/etc/init.d/00thumb
echo "" >> /system/etc/init.d/00thumb
echo "rm -Rf /storage/emulated/0/DCIM/.thumbnails" >> /system/etc/init.d/00thumb
echo "rm -Rf /data/media/0/DCIM/.thumbnails" >> /system/etc/init.d/00thumb
echo "" >> /system/etc/init.d/00thumb
echo "mount -o ro,remount /data" >> /system/etc/init.d/00thumb
echo "" >> /system/etc/init.d/00thumb
chmod 755 /system/etc/init.d/00thumb
mount -o ro,remount /system

