#!/system/bin/sh
# HEBF
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

HEBF=/system/etc/HEBF/Wifi_sleeper.log

 rm -rf $HEBF
 touch $HEBF

 echo "# HEBF_WiFi_Sleeper" | busybox tee -a $HEBF
 echo "" | busybox tee -a $HEBF #Ctrl + v failed attemp
 echo "$( date +"%m-%d-%Y %H:%M:%S" ) Activating wifi sleeper" | busybox tee -a $HEBF

# wifi_idle_wait value = 15 seconds
sqlite=/system/xbin/sqlite3
wifi_idle_wait=15000

RETURN_VALUE=$($sqlite /data/data/com.android.providers.settings/databases/settings.db "select value from secure where name='wifi_idle_ms'")

if [ $RETURN_VALUE='' ]; then
   $sqlite /data/data/com.android.providers.settings/databases/settings.db "insert into secure (name, value) values ('wifi_idle_ms', $wifi_idle_wait )"
else
   $sqlite /data/data/com.android.providers.settings/databases/settings.db "update secure set value=$wifi_idle_wait where name='wifi_idle_ms'"
fi

 echo "" | busybox tee -a $HEBF
 echo "$( date +"%m-%d-%Y %H:%M:%S" ) Wifi sleeper activated" | busybox tee -a $HEBF
